# Generated by Django 4.2.5 on 2023-10-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='userAdmin',
            new_name='useradmin',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='userName',
            new_name='username',
        ),
    ]
