# Generated by Django 4.2.5 on 2023-10-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_lastname_usuario_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
