# Generated by Django 4.2.5 on 2023-10-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='useradmin',
            new_name='is_staff',
        ),
    ]
