# Generated by Django 4.2.5 on 2023-10-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_customusermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserManager',
        ),
    ]
