# Generated by Django 4.2.5 on 2023-10-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='productImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
