# Generated by Django 4.2.5 on 2023-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_price_productos_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='productImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
