# Generated by Django 4.2.5 on 2023-10-21 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0002_productos_userproduct'),
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contizacion',
            name='nameProductCt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productos'),
        ),
        migrations.AlterField(
            model_name='contizacion',
            name='userCt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
