# Generated by Django 4.2.5 on 2023-10-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_contizacion_nameproductct_alter_contizacion_userct'),
    ]

    operations = [
        migrations.AddField(
            model_name='contizacion',
            name='imgProductCt',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contizacion',
            name='valorCt',
            field=models.FloatField(null=True),
        ),
    ]
