# Generated by Django 4.2.5 on 2023-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_contizacion_imgproductct_contizacion_valorct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contizacion',
            name='imgProductCt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
